trigger:
- main

pool: omkar-hcl  # Windows based self-hosted agent

stages:
- stage: BuildCustomImage
  displayName: 'Build Custom Ubuntu Image using Packer + Federation Auth'
  jobs:
  - job: PackerBuildJob
    displayName: 'Run Packer Build'

    steps:
    - task: PowerShell@2
      displayName: 'Install Packer'
      inputs:
        targetType: 'inline'
        script: |
          $packerVersion = "1.11.2"
          $installDir = "$(Build.SourcesDirectory)\packer"
          New-Item -ItemType Directory -Force -Path $installDir | Out-Null
          Invoke-WebRequest -Uri "https://releases.hashicorp.com/packer/$packerVersion/packer_${packerVersion}_windows_amd64.zip" -OutFile "$installDir\packer.zip"
          Expand-Archive "$installDir\packer.zip" -DestinationPath $installDir -Force
          $env:PATH += ";$installDir"
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"

    - task: AzureCLI@2
      displayName: 'Azure Login via Service Connection (Federated)'
      inputs:
        azureSubscription: 'HCL-infrasc'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Logged into Azure successfully via federated credentials"

    - task: PowerShell@2
      displayName: 'Run Packer Build'
      inputs:
        targetType: 'inline'
        script: |
           cd "$(Build.SourcesDirectory)\packer"
           packer init .
           packer build azure-image.pkr.hcl
